Exclude cgotest from stdlib build (#4524)
It didn't build for me with a zig toolchain, but anyway we shouldn't
need to build this for user code

```
# net/internal/cgotest
bazel-out/darwin_arm64-opt-exec-ST-6c94b0e707c0/bin/external/rules_go+/stdlib_/src/net/internal/cgotest/resstate.go:10:10: fatal error: 'resolv.h' file not found
   10 | #include <resolv.h>
```

**What type of PR is this?**
Perf tweak?